[versions]
# Platform
foundation = "1.5.0"
material3 = "<latest_version>"
minSdk = "26"
compileSdk = "34"
targetJvm = "VERSION_17"
kotlin = "1.9.23"
agp = "8.3.2"

# Libs
androidCore = "1.13.1"
preference = "1.2.1"
compose = "1.6.7"
composeCompiler = "1.5.11"
composeMaterial3 = "1.2.1"
accompanist = "0.34.0"
coroutines = "1.8.0"
dagger = "2.49"
okhttp = "4.12.0"
retrofit = "2.9.0"
gson = "2.10.1"
lifecycle = "2.8.1"
timber = "5.0.1"
navigation = "2.7.7"
hiltNavigation = "1.2.0"
appcompat = "1.7.0"
composeActivity = "1.9.1"
ui = "1.5.0"

[libraries]
# Android
android-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidCore" }
android-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
android-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
# Compose
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-runtime-saveable = { module = "androidx.compose.runtime:runtime-saveable", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
# DI
dagger-hilt = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
foundation-v150 = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigation" }
# Google
google-firebase-bom = { module = "com.google.firebase:firebase-bom", version = "32.6.0" }
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
google-firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
# Lifecycle
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
# Kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-collection-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version = "0.3.5" }
# Gradle
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
# Coroutines
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
# Network
material3-vlatestversion = { module = "androidx.compose.material3:material3", version.ref = "material3" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
http-logger = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
gson-converter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
# Navigation
navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
#Logs
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
# Other
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
coil = { module = "io.coil-kt:coil-compose", version = "2.6.0" }
play-ads = { module = "com.google.android.gms:play-services-ads", version = "22.6.0" }
arrow-core = { module = "io.arrow-kt:arrow-core", version = "1.2.0" }
# Norselabs
ui-v150 = { module = "androidx.compose.ui:ui", version.ref = "ui" }
vpn-v2ray = { module = "io.norselabs.vpn:v2ray", version = "0.0.10" }
core-vpn = { module = "io.norselabs.vpn:core_vpn", version = "0.0.7" }
common = { module = "io.norselabs.vpn:common", version = "0.0.2" }
common-map = { module = "io.norselabs.vpn:common_map", version = "0.0.2" }
common-flags = { module = "io.norselabs.vpn:common_flags", version = "0.0.2" }
common-logger = { module = "io.norselabs.vpn:common_logger", version = "0.0.3" }
common-network = { module = "io.norselabs.vpn:common_network", version = "0.0.4" }
common-net-apps = { module = "io.norselabs.vpn:common_net_apps", version = "0.0.1" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
google-crashlytics = { id = "com.google.firebase.crashlytics", version = "2.9.9" }
google-services = { id = "com.google.gms.google-services", version = "4.4.0" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }

[bundles]
compose = [
    "compose-activity",
    "compose-foundation",
    "compose-material3",
    "compose-runtime",
    "compose-layout",
    "compose-ui",
    "compose-ui-tooling",
    "compose-ui-tooling-preview",
    "kotlin-collection-immutable",
]
